### ISSUE TITLE
Milestone 1: Client Setup

### ISSUE THREAD

**Issue by ggwpez** [direct-state-transfer/dst-go#33]
**Discussed in**&emsp; Node meeting 23.4.2020, see `DST/PERUN Node` GDoc.

**Description**&emsp;  
1. For setting up a minimal `go-perun` frame, the following steps serve as guideline:
    - [ ] Import and initialize the ethereum backend
    - [ ] (Inject `levelDB` persistence adapter)) **not yet needed**
    - [ ] Set up a `client.Client`:
      - [ ] Create an `Adjudicator`
      - [ ] Create a `Funder`
      - [ ] Create a `Listener` and listen on it
      - [ ] Create a `Dialer`  
    - [ ] Inject a logger, for example `logrus`  

   To make the client work, a handler for `ChannelProposalReq` needs to be added and started, [see](https://github.com/perun-network/perun-eth-demo/blob/f0aa15b93a4a025f3edb37d28d989115b3f54ca7/cmd/demo/node.go#L291) [and](https://github.com/perun-network/perun-eth-demo/blob/f0aa15b93a4a025f3edb37d28d989115b3f54ca7/cmd/demo/node.go#L246).  
Look at the **Implementation hints** section below for examples.  

2. Some reminders for the specifications:
    - [ ] Derive specifications for remaining components
      - [ ] What do we want to specify? (wallet, identity management and rpc interface, …)
      - [ ] How/Where do we want to specify? (maybe the Wiki?)

**Context**&emsp; This Task should make all new developers familiar with the usage of `go-perun` and help to plan future milestones.  
All options that need to be hard-coded here can be directly used to specify `Milestone 2`.

**Testing**&emsp; Was not discussed, but tests are always appreciated.

**Acceptance criteria**&emsp; 

**Implementation hints**&emsp;  
[client usage](https://github.com/perun-network/perun-eth-demo/tree/f0aa15b93a4a025f3edb37d28d989115b3f54ca7/cmd/demo/node.go#L239)  
[logger injection](https://github.com/perun-network/perun-eth-demo/tree/f0aa15b93a4a025f3edb37d28d989115b3f54ca7/cmd/config.go#L44)  
slightly outdated [godoc](https://pkg.go.dev/perun.network/go-perun@v0.2.0/client?tab=doc)  
[ethereum backend import](https://github.com/perun-network/perun-eth-demo/blob/f0aa15b93a4a025f3edb37d28d989115b3f54ca7/cmd/demo/node.go#L27)

**Comment by manoranjith** [comment]
Hi @ggwpez , 
This issue covers many tasks, that can itself constitute a milestone.  So I have created a [milestone](https://github.com/direct-state-transfer/dst-go/milestone/4) and specific issues to address each task described here. Does the new issues (#38, #39) cover all the points specified here ? In that case, can we close this in the favor of new ones ?

**Comment by ggwpez** [comment]
@manoranjith yes these issues seem to cover it. Thanks for the split up.
